version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install --save-dev firebase-tools
            - run: cp src/config/default/ownplate-dev.js src/config/firebase.js
            - run: cp configs/.firebaserc ./
            - run: GAPIKey=$GAPIKey npm run build
            - run: cp dist/index.html functions/templates/index.html
            - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --project=staging --only hosting
            - run: cd functions && npm install && ../node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --project=staging --only functions

workflows:
    version: 2.1
    build-and-test:
      jobs:
        - build-and-test:
            filters:
              branches:
                only: master
